version: "3.5"
services:
  php_fpm:
      build: .
      container_name: abc_app
      working_dir: /usr/share/nginx/abc
      networks:
        - abc
      volumes:
          - ./:/usr/share/nginx/abc
  nginx:
      image: nginx:1.15
      container_name: abc_nginx
      working_dir: /usr/share/nginx/abc
      networks:
        - abc
      ports:
          - "9090:80"
      volumes:
          - ./:/usr/share/nginx/abc
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
      image: mysql:5.7
      container_name: abc_mysql
      networks:
        - abc
      environment:
        - MYSQL_DATABASE=abc
        - MYSQL_ROOT_PASSWORD=ajimotiJohn
        - MYSQL_USER=abcer
        - MYSQL_PASSWORD=ajimotiJohn

  pma:
    container_name: abc-pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "55699:80"
    environment:
      - "PMA_HOST=abc_mysql"
      - "MYSQL_DATABASE=abc"
      - "MYSQL_ROOT_PASSWORD=ajimotiJohn"
    networks:
      - abc

networks:
  abc:
    driver: bridge
